### ISSUE TITLE
Support VAOs?

### ISSUE THREAD

**Issue by greggman** [greggman/twgl.js#11]
BufferInfo is kind of a VAO in a sense. Should look into optionally supporting them. Maybe call `twgl.useVAOsIfAvailable()` or maybe something more generic like `twgl.configure({ useVAOS: true })`

**Comment by greggman** [comment]
I don't want twgl to impose VAOs but I'm wondering what it should do. VAOs are emulated in Chrome and Firefox for devices that don't support VAOs. Safari which pretty much only has a market on OSX/iOS both of those platforms support VAOs. So that leaves IE12 (not emulated) and Edge (no idea).

They are also always available in WebGL 2

VAOs are much faster than without. For a typical 3 attribute mesh it's 1 call v.s. 6+

How can twgl help here? Just thinking out loud

     var vao = vaoExt.createVertexArrayOES();
     vaoExt.bindVertexArrayOES(vao);
     twgl.SetBuffersAndAttribs(gl, programInfo, bufferInfo);
    
Your VAO is now usable with just binding it.  

I could make twgl just use them if available or make it an option `twgl.setDefaults({useVAOs: true})`? Or maybe the above is enough and twgl doesn't need to do anything? 

I guess I like the idea that `twgl.setBuffersAndAttributes` does or can do the fastest thing. Maybe setting a default is best, no change to API? Or maybe a separate function `twgl.createVAO(gl, programInfo, bufferInfo).  Interestingly a problem is that a VAO is not associated with a program but the programInfo is currently needed to know which attributes to assign which buffers.

The same is true for Uniform Buffer Objects. #24

**Comment by ColaColin** [comment]
I'd prefer it to automatically do the best thing. In my own project I now extended twgl a little to make it work like this:
1. When creating the BufferInfo add an empty VAO to it if VAOs are supported. Also add a flag "vaoInitComplete"
2. When calling setBuffersAndAttributes in the rendering loop if the vao is set but is not initalized use the given programInfo to do the full blown buffer/vertex attribute setup, but target the VAO. Set the flag to true. From here on it will use the VAOs.

This cut the gl calls down by ~60% in a complex scene.

So I use the VAO kind of like lazy initialized cache, to work around the issue that at the buffer initialization time there is no ProgramInfo to set the vertex attributes correctly.
This way on browsers without VAOs I'll just work as well, as it simply keeps using the normal path to set attributes.

**Comment by greggman** [comment]
A problem with automatically doing it is as WebGL is stateful it can cause problems. User calls createBufferInfo or something similar and now a VBO is set. Then user does some manual attribute manipulation and doesn't realize they're manipulating the VBO instead of the default attributes

Your cache idea works.

Maybe should add `setBuffersAndAttributesVAO` that does the same

OR

Maybe just `createVertexArrrayObject(gl, programInfo, bufferInfo)` and `setVertexArrayObject(gl, vao)` and just make them work whether or not the system supports VAOs.

OR

`addVertexArrayObject(gl, programInfo, bufferInfo)` which adds the fields to `bufferInfo` so that `setBuffersAndAttributes` use a VAO? The problem again with that one though is again not realizing a VAO is bound.

Hmmm. I guess people that use VAOs generally use them for everything so maybe I shouldn't worry about that

**Comment by ColaColin** [comment]
That "didn't realize a VBO is bound" was the issue that prevented my own implementation from working directly. So yeah that is a problem, albeit it happened only once to me when I first introduced VAOs into my code, as I still had some manual attribute manipulation. Not quite sure how to prevent it the best, in my own solution I have added an unbind() function to ProgramInfo that unbinds buffers and VAOs used. So between setBuffersAndAttributes() and unbind() I now need to remember that a VAO is bound, since the initial problem that hasn't caused issues for me anymore at least.

**Comment by greggman** [comment]
Thinking about it some more I don't think twgl can make VAOs automatic.

On top of requiring a `ProgramInfo` they are different for different programs. If one program uses `position` and `normal` attributes and another uses `position`, `texcoord` they'll have incompatible attribute assignments which means the same VAO won't work for each program whereas the same `BufferInfo` will work.

In WebGL 1 you can get around that by assigning attribute locations. In WebGL 2 you can set locations in the shaders. But ... that's only something the end user can do, twgl can't do it for you so it seems like it would be wrong for twgl to assume stuff like that.

I think a helper like

    var vao = twgl.createVertexArrayObject(gl, programInfo, bufferInfo);

Is probably what twgl should do because you need one VAO per mesh per program (if the attributes are different). 

Twgl could simulate VAOs on devices that don't have VAOs so you could use that code anywhere. OR, conversely you could just include [a polyfill for VAOs](https://github.com/KhronosGroup/WebGL/blob/master/sdk/demos/google/resources/OESVertexArrayObject.js)

**Comment by floooh** [comment]
Apologies for intruding :) I had implemented VAOs in my emscripten+WebGL engine mainly because it would reduce the number of GL calls drastically, but in the end I removed it again, because I ran into a combinatorial explosion problem if using several input meshes (e.g. for instancing, or if part of the vertex data is static and another is dynamic). I had situations where the combination of input vertex buffers changed, for instance the dynamically updated vertex buffer would change between drawcalls or frames, but the static vertex buffer remained the same. In this case I would have to create one VAO for every possible combination, which became quite ugly soon.

In the end I removed VAO support completely again, and instead update vertex-attrib-pointers only if they have changed. Since usually there are only very few different vertex layouts, this also gave a nice reduction of calls into GL, but this didn't suffer from the combinatorial explosion problem described above.

This is what the code looks like (it's C++, which runs on JS/WebGL via emscripten):

https://github.com/floooh/oryol/blob/master/code/Modules/Gfx/gl/glRenderer.cc#L368

**Comment by greggman** [comment]
I think for *most* apps (games) the majority of things rendered have static mesh data so a VAO would be a win. For those cases where it's not (like your case) you just wouldn't use a VAO?

**Comment by floooh** [comment]
That would be an option too I guess, but I haven't seen a real performance difference after I had implemented the vertex-attribute-pointer state cache so I opted for not using VAOs at all (on desktop GL where VAOs are required in Core Profile, I simply create one global VAO at startup).

**Comment by greggman** [comment]
So I checked in some VAO support. Example here

https://twgljs.org/examples/vertex-array-objects.html

**Comment by greggman** [comment]
Thinking more about VAOs I think if you want to use VAOs it seems like you probably should always manually choose attribute locations. That way you can make sure you only ever need 1 VAO. There should be no explosion of combinations.

In WebGL 1 with twgl you can do that by passing an array of attribute names to `createProgramInfo` as in

    var attribNames = [
        'position',   // position is location 0
        'texcoord',   // texcoord is location 1
        'normal',     // normal is location 2
        'color',      // color is location 3
        'binormal',   // binormal is location 4
        'tangent',    // tangent is location 5
    ];
    var prg = twgl.createProgramInfo(gs, ['vs', 'fs'], attribNames);

It's safe to pass in names you're not using. You can also optionally pass in a parallel array for locations if they aren't consecutive.

In WebGL 2 you can declare them in the shader. It's probably best to create some constants

```
#define LOC_POSITION 0
#define LOC_TEXCOORD 1
#define LOC_NORMAL 2
#define LOC_COLOR 3
#define LOC_BINORMAL 4
#define LOC_TANGENT 5

layout(location = LOC_POSITION) in vec4 position;
layout(location = LOC_TEXCOORD) in vec2 texcoord;
layout(location = LOC_NORMAL) in vec3 normal;
layout(location = LOC_COLOR) in vec4 color;
layout(location = LOC_BINORMAL) in vec3 binormal;
layout(location = LOC_TANGET) in vec3 tangent;
```

etc....  

I'm not sure which is better. Using `gl.bindAttribLocation` which is what the first style does works in both WebGL1 and WebGL2. It also seems maybe more D.R.Y.? The 2nd can be D.R.Y. ish as well if you're generating you shaders.

**Comment by greggman** [comment]
For twgl's first method I could also make it take an object

```js
var attribLocationMap = {
  position: 0,
  texcoord: 1,
  normal: 2,
  color: 3,
  binormal: 4,
  tangent: 5,
};
var prg = twgl.createProgramInfo(gs, ['vs', 'fs'], attribLocationMap);
```

This would have the added benefit that you could specify overlapping mutually-exclusive mappings. Not sure how often that would come up.
