### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by munrocket** [greggman/twgl.js#110]
TWGL library does not use any of the usual open source licenses, such as MIT, LGPL, BSD. As I understand we have a problem with commercial or other traditional opensource software that used TWGL library, am I right? Can I use it in my [software](https://github.com/munrocket/deep-fractal) wich is under MIT? (but it will be changed to strict GPL in next commit).

**Comment by greggman** [comment]
TWGL is MIT

https://github.com/greggman/twgl.js/blob/master/LICENSE.md

**Comment by munrocket** [comment]
Ha-ha, ok :D 
It's actually "University of Illinois/NCSA Open Source License" and combine MIT and BSD licenses.

**Comment by greggman** [comment]
You are right. It's the BSD License 2.0

https://en.wikipedia.org/wiki/BSD_licenses#3-clause_license_(%22BSD_License_2.0%22,_%22Revised_BSD_License%22,_%22New_BSD_License%22,_or_%22Modified_BSD_License%22)

Guess I copied it from some project that also mistakenly thought it was MIT

**Comment by munrocket** [comment]
Ty
