### ISSUE TITLE
Cross-origin texture loads fail

### ISSUE THREAD

**Issue by shawwn** [greggman/twgl.js#119]
See https://webglfundamentals.org/webgl/lessons/webgl-cors-permission.html for an explanation of the problem.

**Comment by shawwn** [comment]
I think the solution is to set
```
twgl.setDefaults({crossOrigin: ""});
```
according to the source code of http://twgljs.org/examples/crossorigin.html

**Comment by greggman** [comment]
You shouldn't need that either. I removed it and things work. Is there some other bug you're running into?
