### ISSUE TITLE
import syntax is broken

### ISSUE THREAD

**Issue by soulofmischief** [greggman/twgl.js#122]
`import twgl from 'twgl.js'` returns undefined.

Related: 
https://github.com/greggman/twgl.js/issues/7
https://github.com/greggman/twgl.js/issues/108

**Comment by TurtlePU** [comment]
I've experienced the same problem while trying to write some TypeScript code.

In 'modules' example, TWGL is imported from src/, so current workaround can be either cloning the whole src/ directory or doing some Rollup:

```bash
$ npm i -g rollup
$ git clone git://github.com/greggman/twgl.js
$ cd twgl.js
$ rollup src/twgl-full.js -o twgl-full-module.js -f esm
```

This creates ```twgl-full-module.js``` file which can be minified/imported/etc and used like this:

```js
import * as twgl from './path/to/twgl-full-module.js'
```

**Comment by soulofmischief** [comment]
Yeah, I did something similar, symlinking `twgl`'s `/src` directory into an external lib folder and just folding `m4.js` into my internal lib.

@greggman I don't mind doing a PR that overhauls your whole build system if you're not too opinionated as long as it works correctly.

**Comment by greggman** [comment]
@soulofmischief 

well I probably am opinionated 😅but would be happy to *look* at a PR to see what you're proposing.

**Comment by greggman** [comment]
Let me add when I original started this project bower was still a thing. People used pre-made ready to use `<script>` based client side libraries. babel was not a thing. Webpack / rollup / parcel were not things.

I'm all for supporting modules but I'm not so much for breaking older stuff

**Comment by soulofmischief** [comment]
Ok, when I get time next weekend I'll PR a rollup config that should maintain backwards compatibility with existing formats while providing module support and we'll go from there.

**Comment by Elvynia** [comment]
@greggman, @soulofmischief, thanks a lot I'm waiting for this ! I recently went into stencil.js and it only understand es5 modules.

Thanks to @TurtlePU I used rollup to cheat in my node_modules for now.

**Comment by soulofmischief** [comment]
@Elvynia my apologies, this completely slipped my mind. I'll get to it this weekend definitely.

**Comment by munrocket** [comment]
@greggman we just need new examples with parcel and codesandbox :D

**Comment by soulofmischief** [comment]
I spent all weekend chasing what turned out to be a kernel bug in the new 5.x kernel which totally took down my PC, so I'll try to tackle it again this weekend.

**Comment by backspaces** [comment]
Isn't the OPs example illegal import format?
> import twgl from 'twgl.js' 

is illegal, it needs to be
> import twgl from './twgl.js' 

or some other form of legal path.

**Comment by Elvynia** [comment]
@backspaces I think the right import would be `import * as twgl from 'twgl.js';` but I might be wrong, anyway that's what I use and it works !

@soulofmischief Don't worry if you don't have time ;) I'm struggling more with the heatwave than with computers these days...

**Comment by backspaces** [comment]
> @backspaces I think the right import would be import * as twgl from 'twgl.js'; but I might be wrong, anyway that's what I use and it works !

Ah, so no "default" export? That's fine. But the path has to be legal so it would be:
> import * as twgl from './twgl.js'

I.e. the twgl.js file must be a complete path, typically being ./twgl.js or ../twgl.js or ../stuff/twgl.js etc

**Comment by Elvynia** [comment]
@backspaces The import I use is for TypeScript files with twgl installed as NPM package, it's not possible to use relative path that way.

**Comment by Elvynia** [comment]
@soulofmischief Any news on when you'll be able to PR that rollup config ? :)

**Comment by soulofmischief** [comment]
haha I got sidetracked by a few big projects but I've made some time. I didn't realize how much time had passed. Thanks for pinging me. I'll get right on it this weekend.

**Comment by soulofmischief** [comment]
Something came up last week, but I had some time to look into things today.

It seems the issue is quite simple, `twgl.js` lacks a default export.

@greggman It just depends on if you want a default export or not. Currently you have named exports, which is fine as long as this is reflected in the docs. So you have to import each export, ex. `import { getContext } from 'twgl.js'` This enables tree shaking and such though some users are used to consuming default exports.

After some experimenting it seems that, if you want to keep tree shaking, the only change required for `import twgl from 'twgl.js` to work as expected is to copy the named export section and add a `default` keyword, ex:

```
// Named exports
export {
  addExtensionsToContext,
  getContext,
  getWebGLContext,
  resizeCanvasToDisplaySize,
  setDefaults,

  attributes,
  draw,
  framebuffers,
  programs,
  textures,
  typedarrays,
  utils,
  vertexArrays,
};

// Default export
export default {
  addExtensionsToContext,
  getContext,
  getWebGLContext,
  resizeCanvasToDisplaySize,
  setDefaults,

  attributes,
  draw,
  framebuffers,
  programs,
  textures,
  typedarrays,
  utils,
  vertexArrays,
};
```

This certainly isn't DRY, so I'll leave the decision up to you.

**Comment by greggman** [comment]
the default above will not allow this

```
import twgl from `./twgl.js`;
...
twgl.createProgramInfo(...);
```

since `createProgramInfo` is not exported on that default object.

You could do this though

```
import twgl from `./twgl.js`;
...
twgl.programs.createProgramInfo(...);
```

Is that acceptable?

Otherwise I can build an object to export everything like this

https://github.com/greggman/twgl.js/pull/138/files

note I also stumbled on this 😅

https://humanwhocodes.com/blog/2019/01/stop-using-default-exports-javascript-module/

**Comment by soulofmischief** [comment]
You're right, that will prevent tree shaking.

Either

```
import * as programs from './programs.js'

const { createProgramInfo } = programs
```

or

```
import * as programs from './programs.js'
import { createProgramInfo } from './programs.js'
```

plus

```
export default {
// other exports
createProgramInfo
}
```

should do the trick, though. 

I've read that article before and I completely disagree with the author. They're reaching for straws.

A couple of points:

> If I don’t own list.js, then I may open up some documentation.

I've never heard of using a module without glancing at the README or docs to understand what exactly it is you're using. Class, object, literal, whatever... you don't just import something and start using it without knowing what it is.

> The benefit is that I can easily search for everywhere that LinkedList is used in a code base and know that it all refers to the same LinkedList

...if you import a default export from a particular module or file, it will also be the same export every time. I don't even understand the author's thinking here. It takes a simple search of the module path to get every import declaration, named or default.

> Named exports in JavaScript modules have a particular advantage over default exports in that an error is thrown when attempting to import something that doesn’t exist in the module.

No, it depends on how you access the named module. It often just returns undefined, just like a missing default export.

---

My typical approach is to do default exports where it makes sense, and named exports elsewhere. If doing both is an option, as it seems here, it also doesn't hurt to have both. It depends on if you view twgl as a module with submodules or just a collection of related but independent modules.

**Comment by greggman** [comment]
I view twgl as collection of functions so

```
import * as twgl from `twgl.js`;
```

is the correct syntax if you want all the functions. Otherwise import what you want

```
import {
  createProgramInfo,
  createTexture,
  createBufferInfoFromArrays,
  setBuffersAndAttributes,
  setUniforms,
  drawBufferInfo,
} from `twgl`;
```

**Comment by soulofmischief** [comment]
Welp, problem solved. It would be a good idea to stick that import declaration in the docs somewhere as there was no documented way to use the npm module.

@Elvynia Sorry it took so long to resolve this!

**Comment by Elvynia** [comment]
@soulofmischief, @greggman Thank you very much for this ! I'm going to use it this weekend ! :)

**Comment by Elvynia** [comment]
@soulofmischief, @greggman Hi and sorry for popping again now that the issue is closed but... I still need your help :worried: My project uses TypeScript with this config :
```json
{
    "compilerOptions": {
        "target": "es2017",
        "module": "es2015",
        "outDir": "dist",
        "removeComments": true,
        "moduleResolution": "node",
        "experimentalDecorators": true,
        "declaration": true,
        "preserveSymlinks": true,
        "sourceMap": true,
        "lib": [
            "dom",
            "es2017"
        ]
    },
    "exclude": [
        "node_modules",
        "dist",
        "build"
    ]
}
```
(Using "module" with "es6" or "esnext" produce the same errors)

After using tsc to transpile in dist/ I use polymer-cli to serve my files.
If I don't run the babel solution from @TurtlePU and I use the following import in ts files :
```TypeScript
import { createProgramInfo, createBufferInfoFromArrays, setBuffersAndAttributes,
    setUniforms, drawBufferInfo } from 'twgl.js';
```
(btw the npm package is `twgl.js` not `twgl` or I'm missing something !)

Then polymer-cli transform the import into :
```JavaScript
import { createProgramInfo, createBufferInfoFromArrays, setBuffersAndAttributes,
    setUniforms, drawBufferInfo } from "../../../../node_modules/twgl.js/dist/4.x/twgl-full.js";
```

The path is correct, but at runtime I get the following errors :
```
Uncaught SyntaxError: The requested module '../../../../node_modules/twgl.js/dist/4.x/twgl-full.js' does not provide an export named 'resizeCanvasToDisplaySize'
(index):1 Uncaught SyntaxError: The requested module '../../../../node_modules/twgl.js/dist/4.x/twgl-full.js' does not provide an export named 'setUniforms'
(index):1 Uncaught SyntaxError: The requested module '../../../../node_modules/twgl.js/dist/4.x/twgl-full.js' does not provide an export named 'm4'
(index):1 Uncaught SyntaxError: The requested module '../../../../node_modules/twgl.js/dist/4.x/twgl-full.js' does not provide an export named 'setUniforms'
(index):1 Uncaught SyntaxError: The requested module '../../../../node_modules/twgl.js/dist/4.x/twgl-full.js' does not provide an export named 'm4'
```
I know there is a `node_modules/twgl.js/dist/4.x/twgl.js` file but the `package.json` target the other one, I can't test if it would make a difference.

Did I miss something from your conversation on this issue ? :open_mouth:
