### ISSUE TITLE
out of date function signatures

### ISSUE THREAD

**Issue by demskie** [greggman/twgl.js#135]
the "WebGLRenderingContext" parameter is missing from the following docs:

https://github.com/greggman/twgl.js/blob/a90ce8ef2083fd6185fa30cc8972aafc28cc68d7/dist/4.x/twgl.d.ts#L251
https://github.com/greggman/twgl.js/blob/a90ce8ef2083fd6185fa30cc8972aafc28cc68d7/dist/4.x/twgl.d.ts#L267
https://github.com/greggman/twgl.js/blob/a90ce8ef2083fd6185fa30cc8972aafc28cc68d7/src/programs.js#L828-L838
https://github.com/greggman/twgl.js/blob/a90ce8ef2083fd6185fa30cc8972aafc28cc68d7/src/programs.js#L1393-L1402

**Comment by greggman** [comment]
this has been fixed
