### ISSUE TITLE
twgl.attributes is no longer exported

### ISSUE THREAD

**Issue by legends2k** [greggman/twgl.js#137]
Upgrading from 3.6.0 to 4.11.1, I see that `twgl.attributes` is no longer exported.  Functions like `createAttribsFromArrays` are available directly under `twgl` but not under `twgl.attributes` unlike what [twgl/attributes' documentation](http://twgljs.org/docs/module-twgl_attributes.html) says:

> For backward compatibility they are available at both `twgl.attributes` and `twgl itself`

If it helps, I use twgl.js in the dumbest possible way: `<script type="text/javascript" src="twgl-full.js"></script>` in my html document within `<head>`.

**Comment by greggman** [comment]
doh! try 4.11.12?

**Comment by legends2k** [comment]
You mean 4.11.2, yeah, that solves it 👍
