### ISSUE TITLE
CommonJS issues

### ISSUE THREAD

**Issue by Prinzhorn** [greggman/twgl.js#14]
I'm trying to use twgl with browserify. There are two small issues.

1. I need to use `var twgl = require('twgl.js').twgl;` because for some reason twgl exports an object with a `twgl` property instead of exporting itself

2. The `main` in package.json points to the minified file. This makes it impossible to debug locally. I'm not sure though if that was intended?

**Comment by greggman** [comment]
Try it now, v0.0.30. 

I've never used CommonJS outside of node and I had not used browserify. Had to hack a bunch of crap. Not sure if there's a more common solution but it seems to be working

http://twgljs.org/examples/browserify.html

**Comment by Prinzhorn** [comment]
Awesome, it's working as expected now!

> I've never used CommonJS outside of node and I had not used browserify.

I created a simple browserify example using your "tiny" example. I believe this is **so** much cleaner and better than anything else. I'm just getting into WebGL and couldn't believe that very demo and tutorial I see uses script tags. Who would do this in production?

https://github.com/Prinzhorn/twgl-browserify

```
git clone git@github.com:Prinzhorn/twgl-browserify.git
cd twgl-browserify
npm install
npm run watch
```

Now you're up and running. Your `bundle.js` (which index.html references) automatically gets updated when you changed `index.js` or **any of the two shader files**. You're welcome. (I personally combine this with harp and browser-sync).

**Comment by greggman** [comment]
Lots of people prefer AMD over CommonJS myself included.

CommonJS requires a compile step, AMD does not but can still be compiled for production. As for script tags, 99% of devs still don't use either AMD or CommonJS so asking them to learn something else before they can use a library is generally a great way to get them not to use it :P

**Comment by Prinzhorn** [comment]
> so asking them to learn something else before they can use a library is generally a great way to get them not to use it

It was not my intend to force anyone into CommonJS at all. I just found it weird to inline something (without having syntax highlighting etc.). I guess it will also get ugly once you need more than one fragment and vertex shader and start using weird IDs and reinvent some structure on top of it.

**Comment by greggman** [comment]
Plenty of good editors can syntax highlight embedded languages no problem.

As for bigger projects, sure. But bigger projects need all kinds of build
infrastructure. Not just JS concatenation and compression but image
processing steps, 3D asset conditioning steps, sound processing steps, font
glyph generation steps, localization data extraction steps, etc etc.
Shaders is yet another part of that. Engines like unreal/unity can generate
~5000 shaders at build time. It's still far easier to show a single page
example IMO. Want to see how it works right click and look. No digging
through 4,5,6 files

**Comment by Prinzhorn** [comment]
Good points. Thanks for creating twgl!
