### ISSUE TITLE
typescript Qaud primitives returns wrong types

### ISSUE THREAD

**Issue by Zaitsev** [greggman/twgl.js#142]
Seems that types are swapped...
```typescript
    export function createXYQuadBufferInfo(gl: WebGLRenderingContext, size?: number, xOffset?: number, yOffset?: number): {
        [key: string]: WebGLBuffer;
    };
    export function createXYQuadBuffers(gl: WebGLRenderingContext, size?: number, xOffset?: number, yOffset?: number): BufferInfo;

```

**Comment by Zaitsev** [comment]
also in typsecript:
```typescript
export function bindFramebufferInfo(gl: WebGLRenderingContext, framebufferInfo?: FramebufferInfo, target?: number): void;
```
calling  it as `twgl.bindFramebufferInfo(gl, null)` has more clear intention to _unbind_ (we pass null, and this is consistent with gl.bindFremabuffer) so may be its better to define it as `framebufferInfo: FramebufferInfo|null`  (required nullable parameter or make it nullable optional for backward compability)

**Comment by greggman** [comment]
made both of those changes. 

2a2a841f516d98da72ca9b5c63b44b28ef8f8f7e

9965723a31ade9fdc555a39184e55982ca3f3f66


Funny that even though the documentation says passing no 2nd parameter to `twgl.bindFramebufferIInfo` binds the canvas I always passed `null` in actual usage 😅

**Comment by Zaitsev** [comment]
If not passed will ~bind~ the canvas
If not passed or null will *unbind* the buffer
