### ISSUE TITLE
m4.setAxis documentation is incorrect

### ISSUE THREAD

**Issue by ViktorCosenza** [greggman/twgl.js#144]
The signature in the documentation is (vector, axis, dst) but the actual signature is (original, vector, axis, dst), one of the arguments is missing from the documentation. 
Calling the function with the signature from the documentation does not match the expected behaviour (setting the correct axis).   

https://github.com/greggman/twgl.js/blob/dba4491b6b11df680a6c33714faea3924440d5a2/src/m4.js#L464-L480
This is the documentation as of today, 2019/10/21.Found at https://twgljs.org/docs/module-twgl_m4.html#.setAxis
![image](https://user-images.githubusercontent.com/30510937/67246133-01f7bb00-f434-11e9-9b69-cdb4fd6d4098.png)

**Comment by greggman** [comment]
thanks! fixed https://github.com/greggman/twgl.js/commit/35131cdbcf00b3f1030884c5ada0346e89bdd34b

<img width="722" alt="Screen Shot 2019-10-23 at 17 35 48" src="https://user-images.githubusercontent.com/234804/67374038-99d3e100-f5bb-11e9-954b-d5d58d9e3d28.png">

**Comment by ViktorCosenza** [comment]
Very nice, thanks!
