### ISSUE TITLE
ESM Version?

### ISSUE THREAD

**Issue by strutcode** [greggman/twgl.js#146]
Is there any interest in providing an ES6 module version of the library to enable tree shaking? The structure of the library makes it ideal for such an application and the source files are already partially using module syntax.

**Comment by greggman** [comment]
You have any idea which is better?

A. rollup the src to a single file, twgl.module.js, add `"module": "dist/twgl.module.js" to package.json

B. just include the src folder in files,  add `"module": "src/twgl.js" to package.json

**Comment by zorro-fr24** [comment]
I can report at least that tree-shaking works with webpack/babel if you selectively import from src/twgl.js, eg:

```javascript
import {
	createFramebufferInfo,
	createTexture,
	resizeFramebufferInfo,
	setTextureFromArray,
	drawBufferInfo,
	bindFramebufferInfo
} from 'twgl.js/twgl';```

original file sizes:

![image](https://user-images.githubusercontent.com/7267001/67424202-ffcd6200-f5d5-11e9-9a32-f82a374e251d.png)

vs actual code bundled

![image](https://user-images.githubusercontent.com/7267001/67425327-1379c800-f5d8-11e9-9e17-45e6f5ab4d16.png)

or a neat 26kb once minified/compressed

**Comment by strutcode** [comment]
@zorro-fr24 Thansk for the tip! I did toy around with that since I noticed the source was written in es module syntax but there are two problems:
1. The npm package doesn't include the source so you would have to use this repo as your dependency
2. The Typescript definitions aren't in the src directory so TS complains about the lack of typings and doesn't provide completeion

@greggman I think option A would be nicer since you can always just reference `twgl.js` as your import, instead of finding the particular thing you're looking for from the source files or doing a bunch of `import as` stuff. I would be happy with either option though!

**Comment by greggman** [comment]
I went for option a. I tested and it still shakes the tree

**Comment by strutcode** [comment]
You are awesome! Thanks so much for doing that. I was going to offer to contribute a pull request but it seems like you have it all under control. Consider this case closed.
