### ISSUE TITLE
Follow semver

### ISSUE THREAD

**Issue by Prinzhorn** [greggman/twgl.js#15]
This is related to #14 but a different discussion. The changes made for better browserify/CommonJS support are breaking changes and should bump the major version. Otherwise if I use `"twgl": "0.0.x"` or `"twgl": "^0.0.27"` or `"twgl": "~0.0.27"` and do a `npm update` my build breaks. I won't matter much now since it's already on npm, but it's something to consider in the future.

**Comment by greggman** [comment]
Maybe I'm mis-understanding. It never worked with browserify/CommonJS before so nothing broke

**Comment by Prinzhorn** [comment]
> Maybe I'm mis-understanding. It never worked with browserify/CommonJS before so nothing broke.

It was working fine when I used `var twgl = require('twgl.js').twgl;`. But if it was never supposed to work then I agree that it's not a breaking change.

> Also, according to semver, anything that is major version 0 can break things whenever it wants.

You're right. But there's a risk that many modules stay `0.x` for **years** and always argue that they can break things whenever they want. That's why we're now having node 4.x and soon 5.x, because they finally follow semver. But once we get used to regularly incrementing the major it's not a problem any more, albeit "weird" in the first moment.

But anyway, I don't want to get into semver discussions here :)
