### ISSUE TITLE
AttachmentOptions definition is missing "internalFormat?: number" field

### ISSUE THREAD

**Issue by baturinsky** [greggman/twgl.js#151]
In twgl-full.d.ts and twgl.d.ts definition of AttachmentOptions has no field "internalFormat". 
It makes it impossible to use it with WebGL2 formats such as RGBA16F in typescript (without passing it an already created texture).

**Comment by greggman** [comment]
https://github.com/greggman/twgl.js/commit/508cd8897b598d8f47b0e3e9aa3cbad7d6e31766

**Comment by baturinsky** [comment]
But https://github.com/greggman/twgl.js/blob/master/dist/4.x/twgl.d.ts (and twgl-full.d.ts there) STILL have no internalFormat in AttachmentOptions  definition.
