### ISSUE TITLE
twgl-full.module.js has wrong version in comment header

### ISSUE THREAD

**Issue by legends2k** [greggman/twgl.js#158]
`twgl.js-4.14.0.tar.gz/dist/4.x/twgl-full.module.js` has version 4.13.1 in comment header.

> @license twgl.js 4.13.1 Copyright (c) 2015, Gregg Tavares All Rights Reserved.
> Available via the MIT license.
> see: http://github.com/greggman/twgl.js for details

However, `twgl.js` and `twgl-full.js` have versions in comment matching the release version.

> @license twgl.js 4.14.0 Copyright (c) 2015, Gregg Tavares All Rights Reserved.
> Available via the MIT license.
> see: http://github.com/greggman/twgl.js for details

**Comment by greggman** [comment]
thanks. fixed
https://github.com/greggman/twgl.js/commit/d8c7142ca48c0cae4f4f1b38549c1138025153a9
