### ISSUE TITLE
[expo-gl][react-native]support expo-gl version of gl.texImage2D

### ISSUE THREAD

**Issue by wood1986** [greggman/twgl.js#163]
https://github.com/greggman/twgl.js/blob/addd2f6ca5fd2d7ea551eb73f981e90397026508/src/textures.js#L1646-L1652

Is it possible to change from throw to not throw with warning message?

In [expo-gl](https://docs.expo.io/versions/latest/sdk/gl-view/) version of gl.texImage2D, the last argument is in { width, height, localUri }. See https://youtu.be/xUD4ER_3r_4?t=366

```js
} else {
  if (!isTexImageSource(src)) {
   console.warn("unsupported src type but we will try")
  }
  setTextureFromElement(gl, tex, src, options); 
  width  = src.width; 
  height = src.height; 
}
```

**Comment by greggman** [comment]
I just removed the check.

https://github.com/greggman/twgl.js/commit/0e7464cc8e25fa013add8f663bda9384857c3eff

**Comment by wood1986** [comment]
Thanks. I can close my PR and issue
