### ISSUE TITLE
Performance drop in saveSkipState

### ISSUE THREAD

**Issue by jonajames** [greggman/twgl.js#178]
I have noticed that uploading a js array to a texture takes a lot of time, expecially on mobile devices.

![2021-02-11-225435_676x194_scrot](https://user-images.githubusercontent.com/14654190/107703609-26784600-6cbc-11eb-9c27-ac5fd58f2a39.png)
The picture above shows a 60ms to 140ms time drop when calling getParameter.
https://github.com/greggman/twgl.js/blob/b2d47253b89c8e5099877660f6a79a4f19aca456/src/textures.js#L665

What I'm doing here is using tensorflow js to get a semantic segmentation of a webcam frame and then using webgl to blur and paint back some parts of the image on a canvas.
I have no idea if getParameter is taking so long or if it's just an artefact due to work being done on the GPU, but it seems strange to me.
Could you shed some light on what's the purpose of saveSkipState and if there's some way i can edit it out to see if it's causing the problem?

Thanks

**Comment by tuner** [comment]
I have stumbled upon the same issue too. I worked around it by updating the texture using direct WebGL calls. I don't quite understand all the subtleties of packing and alignment, but I assume that saveSkipState is not always needed(?).

```js
        const gl = this.context.glHelper.gl;
        const options = {
            internalFormat: gl.RG32F,
            format: gl.RG,
            height: 1
        };

        if (this.facetTexture) {
            // Slow because of twgl's unpack-alignment hack:
            //setTextureFromArray(gl, this.facetTexture, arr, options);

            gl.bindTexture(gl.TEXTURE_2D, this.facetTexture);
            gl.texImage2D(
                gl.TEXTURE_2D,
                0,
                options.internalFormat,
                arr.length / 2,
                1,
                0,
                options.format,
                gl.FLOAT,
                arr
            );
        } else {
            this.facetTexture = createTexture(gl, {
                ...options,
                src: arr
            });
        }
```

**Comment by greggman** [comment]
I pushed a version that doesn't save/restore it just sets. Hopefully this won't break anyone.

**Comment by jonajames** [comment]
I this it's a little bit better for me, but not by much, as I expected...
If this starts breaking stuff it may be worth reverting the chnage.
Closing.
