### ISSUE TITLE
setAttribInfoBufferFromArray if offset is given not existing variable buffer is accessed

### ISSUE THREAD

**Issue by ColaColin** [greggman/twgl.js#18]
My usecase does not involve an offset, but reading the code the case offset !== undefined will fail in line 1240: gl.bindBuffer(gl.ARRAY_BUFFER, buffer);
buffer is not defined, should probably be attribInfo.buffer.
I also can't seem to find that method in the API documentation, albeit it has a documentation comment.

**Comment by greggman** [comment]
Thanks for pointing those out. Fixed in https://github.com/greggman/twgl.js/commit/4c18de20583c3cb5c2e4a206581e246f085c1ce1 and published version 0.0.38
