### ISSUE TITLE
How to use vertexAttribIPointer with twgl?

### ISSUE THREAD

**Issue by iMplode-nZ** [greggman/twgl.js#181]
I would like to have integer vectors within the shader, which requires use of [`gl.vertexAttribIPointer`](https://developer.mozilla.org/en-US/docs/Web/API/WebGL2RenderingContext/vertexAttribIPointer). Is it possible to do this with twgl?

**Comment by greggman** [comment]
You either have to pass in int or unit based typed arrays OR tell it the type

https://jsgist.org/?src=de40f6ce9e5b0c98e616c9aa30c1aa4d

**Comment by iMplode-nZ** [comment]
Thanks.
