### ISSUE TITLE
Possible bug with `divisor` (minimal example attached)

### ISSUE THREAD

**Issue by yurivish** [greggman/twgl.js#191]
Hi, thank you so much for this library and your webgl learning resources and stackoverflow answers – they're a real treasure, and have helped me become more confident with low-level graphics programming.

I'm now using twgl for a fun new project, and have run into some interesting behavior that I'm not sure how to resolve.

Here's a [jsgist link](https://jsgist.org/?src=cb64%2CeJyVVdtO3DAQ_ZVpXshKaZZS-rJcJNiyFRIIVLVPLAITexMjx45sZ8MK5d87dq7LpbRSonhmzlyOZ-w8B5LkLJgFlxt4ND-4sUEUGGYtl6kJZs91FKy4YLi86aFcUvYUZzYXiE2UtExaVB-aRPPCgtHJ0U5mbWFm06mtUvFoYqXTKcXg0_34yevinMv40ewcH04bt-Ogjl5kSIzZSvAa8bgNqFCrqphQerZGzQUmZJLpcBl8v7qcN7ALRSijyyCCcAJHx_C8lAAYwlhIiFwTA0dAVVLmiI0TzYhlZ4I5KdxpADsT7-LXccWpzdClFTPG08yi_G13dwicigGRMusrebJYVsUeUrG3DCYHA3jtKrgn1mr-UFoGa5bsQaEMt1xJj9uy7aObUNob1kRvsG-Nen03MihOISdcIufnzuJq8gis7-66TYBK5x12CeOnqE8ebyLYjeDL5ADq-1HFK19xoVnCjQuRM8rLvICVUMT-T2FYx0KTdN5W1wG3sxVapZrk53KlEONnqWnT9WAIUxHBzdpEWNvteHOJ1mTjyvVth57arFMAyDKfq7xQEltuZrAXQWehxJIZLByrr3snLlKsVmFnBfj8JfLvtga2NE7C9yMFOr6M28l--pa2bgF-i94vf7-P81H12Fn3xN-ww-OKURj0W3BneQV_T4_CoP8oq-cIULtPPWrfQ7laMf269ae9fqFV7skZPwNNv90EuCDTKcw9HghIVnWjFEETpdUOSZyhTDgRYgMVx3NO4J7yNTdK33sOGJBICjZjEs-3EIA3Z1OLOZH0pDunOIeamVK4SxW4xDBVxjEf3nyMydhF8mTe8W6bhHyaxb_M_Gvou3vUj84bh8FTbCnPXIdQtBk3yLY0zDjmuF_pJwit3kApE5W7q9Lx9DDBJWub-ebZGkzNeLr9H49oeIM58Qh-jWD_tg_k5wI_XtE11xEVjGh_e4TNuLmnOf6dFRnH86uLq593p78XizP8nP_qEUip3dBwdMvE7bqB_bVRbjtHntFolkbeVJNq6IZ3eonr_0APim5iUhRM0nnGBQ2b3wgyrydBfVv_AWeecCQ%3D) with an example. It should render a multicolored square; uncomment line 46 to see the problem – the square disappears.

The basic idea is that calling `twgl.setBuffersAndAttributes` on one bufferInfo with a  `divisor` property changes the result of rendering a different bufferInfo later. Is this a bug? In my app I’m rendering some stuff with instanced rendering, and then other stuff without, which is how I came across this behavior.

I'm not yet familiar enough with twgl's internals to easily debug further into the library, but got as far as figuring out that the `divisor` setting was the proximal cause.

**Comment by greggman** [comment]
Sorry, there is no easy solution. twgl doesn't keep any state and setting divisor by default would be a waste for anyone not using it.. 

One solution is to add `divisor: 0` to the other things

https://jsgist.org/?src=f6d17a913a5e1418d0348d24199480c5

**Comment by yurivish** [comment]
Thanks! 

Another idea I just had is to user VAOs, passing the first bufferInfo `twgl.createVertexArrayInfo`, which also seems to make the example run ([sample](https://jsgist.org/?src=cb64%2CeJyVVW1P2zAQ_iu3fCGVsgQY-7BuILGOSpOYmKZtXygCk7iJkWNHttNQofz3ne28FcYGUqvEd8_dPed77DwEgpQ0mAemyXl8pxOmdU11cvDhIIgCTY1hItfB_KGNgjXj1KJxeRkwkdH7uDAlR5xfpFoP73c6uPIRFj1U2YlKpTBUGDR_0qlilQGt0uO9wphKz5PEMrrTsVR5kjFtkqP43tnikgnMv3fyKfFhJ0EbPargqYwFniKQ4BTQoFU2Mcmysw1azrEgFVSFq-DLxbeFh51LktFsFUQQzuD4BB5WAgBTaAMpERui4RgymdYlYuNUUWLoGad2Fe55wN7Mhbj3uGGZKTCkWxaU5YXB9fv9_TFxzkdETo1jcm-QVkNvc364CmYfR_DGMrghxih2WxsKG5oeQiU1M0wKh9vxHWEYl8o5NkRtcdLevLmeOCTLoCRMYM8Pvcdycgjkd_29K4BGGx32BeP7aCgebyPYj-Bg9hHamwnjtWNcKZoybVOUNGN1WcGaS2JeQwx5LBXJFx27HrhbrVIyV6T8KtYSMU5LfkzfR0eY8wguNzpCblfTzSVKka2l68YOQ2vz3gAg6nIhy0oKHLmew2EEvScjhsxhabt6d3hqM8VyHfZegLcHkfvvWmDHYlf4_58BAx_n7ddOfSvTdgC3Rc_TP5pm9l2wDdM2BEf50s4Qan_xe5z-tBtcjPYduPU8gT9nx8Vo_19V1z9Aax_tZLS39XpN1VNZ_KYKT5tryknDh6NAOgWMquksk9jPQ86lkqXLoZ22vI48Fasv-5IksHBRQEDQps8cgc_VWUea1lGnjHC-hYbhLULgphvOjaOCCYnIwBRU4O3BOeBN7hnpU5Gd9rcAqlxRXXN7yQMTmKYpGNbDe5VSEdtMrqVnoh9vyEtO1Ct2ahDmX47aRIw4YGzXFExjq7Wm2raNm5W_gdCoLdQilaW9hW2TDsaZoJ0W_npsJ0Wcuu3mTxUeXmJNPN3vIji6GhI5WeHDGfrJ2i45JcpdTKFXq_35m6X3Yrvx4uL84sf151_L5Rk-vv4cENhSt5vhRHFx9-5h_5yS3cupVidCmkRnijTjKFzQY9zwcbuV2TYmVUVFtigYz0L_hcLO21nQXrV_ALz5n2I%3D)).

If I understand them correctly VAOs would provide the kind of isolation between collections of buffers that I'm looking for, and not require extra calls to `gl.vertexAttribDivisor`.

**Comment by greggman** [comment]
yes VAOs would work
