### ISSUE TITLE
TypeError: null is not an object (evaluating 'gl[defaultShaderType[ii]]')

### ISSUE THREAD

**Issue by hyvyys** [greggman/twgl.js#193]
Hi,

I'm getting the following error in Safari 14.1.2 on macOS Big Sur:

TypeError: null is not an object (evaluating 'gl[defaultShaderType[ii]]')

Replication on Codepen:   https://codepen.io/hyvyys/pen/mdpbwGX

**Comment by hyvyys** [comment]
Safari 14 does not support WebGL by default.

**Comment by hyvyys** [comment]
Oh, right. Should've googled "caniuse WebGL 1"!

I guess the refactor of this sample to use WebGL 1 would be too daunting for me right now, I literally only forked that codepen to link it here for posteriority.

**Comment by greggman** [comment]
https://codepen.io/greggman/pen/ExoYBOP
