### ISSUE TITLE
Add support for async shader compilation (KHR_parallel_shader_compile)

### ISSUE THREAD

**Issue by gouldingken** [greggman/twgl.js#196]
Currently twgl will lock up the first time you pass in a complex fragment shader. While in my case the compile time is only a few seconds, this is a non-optimal experience for users as the browser locks up completely across all tabs.

I believe KHR_parallel_shader_compile is the best way to solve this issue, but as I understand it, this would need to be handled within some of the core twgl functionality (programs.js ?).

Some kind of callback providing async updates that could be used to update the user would also really help the UX - possibly like the generator function here:
https://developer.mozilla.org/en-US/docs/Web/API/KHR_parallel_shader_compile

If it's useful here's an example of a PR for implementing this in Three.js: https://github.com/mrdoob/three.js/pull/16662/files#diff-493e8439a196c85be7dd44c0440c167cdf3519d3187988123eea00f0ac697803

**Comment by greggman** [comment]
Okay, I added both a callback version and a promise version

Examples:

via callback

```
twgl.createProgramInfo(gl, [vs, fs], {
  callback(error, programInfo) {
    if (error) { 
      // you got an error 
    } else {
      // use programInfo
  },
});

twgl.createProgram(gl, [vs, fs], {
  callback(error, program) {
    if (error) { 
      // you got an error 
    } else {
      // use program
  },
});
```

via promise

```
const programInfo = await twgl.createProgramInfoAsync(gl, [vs, fs]);
const program = await twgl.createProgram(gl, [vs, fs]);
```

and of course you can use promises with `then`/`catch` etc... if you're not into async await.
It should still work if the browser doesn't support `KHR_parallel_shader_compile` but it will block.

**Comment by gouldingken** [comment]
Just tested and this works great! Sorry if it caused some new bugs (I saw the commits today). Thanks for jumping on it so quickly.

The solution is so easy to implement on existing code - in my case literally just switching that call to async - and the benefit of not worrying about locking up the user's browser is huge - especially on Windows with DirectX.
