### ISSUE TITLE
Last framebuffer's attached texture is empty?

### ISSUE THREAD

**Issue by SuperKenVery** [greggman/twgl.js#202]
It seems that the texture attachment in the last framebuffer created with `twgl.createFramebufferInfo()` will be empty... 

That's super strange, but as far as I can tell, that's what happened. 

Here is [my code](https://github.com/SuperKenVery/wow-lyric). 

It runs roughly like this:

```yaml
index.js: main():
    initialize background
    initialize lyric lines(new LyricPlayer)
            lyric.js:
                new LyricLine:
                    Render this line's text into ImageData
                new LyricLine:
                    Render this line's text into ImageData
                ...
                (Instance of LyricLine).initWebglResources():
                    Put the ImageData into a texture
                    Make  a framebuffer (using the texture) (using twgl.createFramebufferInfo)
                (Instance of LyricLine).initWebglResources():
                    Put the ImageData into a texture
                    Make  a framebuffer (using the texture) (using twgl.createFramebufferInfo)
```

Now please pay attention to `lyrics.js`:`LyricPlayer`'s constructor's last part, where I called

```js
twgl.createFramebufferInfo(this.gl)
```

 - **Without this, the last line of lyric will not show up. With this, it would show up properly.**
 - If I set a breakpoint after initialization and run (last_line.textFramebuffer)=(second_last_line.textFramebuffer), it will be rendered normally, which largely suggests that my code works well but the texture created with twgl went wrong somehow. 

I've reviewed my code for lots of times and didn't find anything wrong with it. I treated the last line of lyric exactly the same like other lines. So I guess it's a bug of `twgl.js`. However, if the mistake is indeed on my side, sorry about that in advance.

**Comment by greggman** [comment]
try changing 

    twgl.createFramebufferInfo(this.gl)

to

    twgl.bindFramebufferInfo(gl, null)

`twgl.createFramebufferInfo` leaves the framebuffer it just created, bound.

Otherwise, any chance you can make a [minimal complete verifiable example](https://ibug.io/blog/2018/06/minimal-complete-verifiable-example/) on something like [jsfiddle.net](https://jsfiddle.net)? I don't think I have time to go through your entire app

**Comment by greggman** [comment]
It occured to me you might also try adding

```
gl.bindTexture(gl.TEXTURE_2D, null);
```

In that same spot.

**Comment by SuperKenVery** [comment]
> twgl.createFramebufferInfo leaves the framebuffer it just created, bound.

Thanks a lot!!! This helped me! 

But I think maybe it's not so good to leave the framebuffer bound when calling `twgl.createFramebufferInfo` ... Maybe you could mention that in the document or unbind it in the code. 

===Below is related to my project, rather than twgl.js===
It turns out that I called 
```js
gl.clearColor(0, 0, 0, 0)
gl.clear(this.gl.COLOR_BUFFER_BIT)
```
After all the framebuffer initialization. That's why it's empty.
