### ISSUE TITLE
resizeCanvasToDisplaySize in a web worker sets the width and height to 0

### ISSUE THREAD

**Issue by adarah** [greggman/twgl.js#206]
I was porting some code which ran in the main thread to a Web Worker via the [OffscreenCanvas API](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas), and I noticed that calling `resizeCanvasToDisplaySize` was making my scene disappear. Is this intended behavior? If so, do you have any recommendations on how to work around this limitation so that I can still have the canvas resizing functionality in the Web Worker?

**Comment by greggman** [comment]
It makes no sense to call `resizeCanvasToDisplaySize` in a worker as there is no display size in a worker. Any display size you want would have to be passed from your main page into the worker and of course twgl would no idea how you're going to do that.

As for ideas, this article shows one way to make a proxy to send this info to your worker.

https://threejs.org/manual/#en/offscreencanvas

**Comment by adarah** [comment]
I see, I'll study that article then, thanks for responding so quickly!
