### ISSUE TITLE
deoptimized setUniforms

### ISSUE THREAD

**Issue by ColaColin** [greggman/twgl.js#21]
setUniforms reassigns a parameter value, which causes chrome to deoptimize the function:
  
Around line 740:
function setUniforms(setters, values) {  // eslint-disable-line
    setters = setters.uniformSetters || setters;

A local variable should be used instead to prevent this.

**Comment by greggman** [comment]
I updated that in v0.0.41   Please give it a try

**Comment by ColaColin** [comment]
Works fine and doesn't show up anymore as deoptimized.
