### ISSUE TITLE
Unsetting a texture in webgl2

### ISSUE THREAD

**Issue by zackgomez** [greggman/twgl.js#217]
Hi,

I have a shader with an optional normal texture param.  The shader samples the texture and uses a default normal on a "black" texel.

This works fine with gl.bindTexture(..., null) in raw webgl2, but when using twgl I am unable to bind the optional texture to null, with setUniforms or the uniform setter directly.

```
      twglProgram.uniformSetters.uNormalTexture(null);
```

Here is a stack trace
![image](https://user-images.githubusercontent.com/354226/204184409-4764c0f3-8bd2-4b0f-8572-0f992d7330cc.png)

Now of course I could (and perhaps should) pass another uniform instead of reading the default value and manually unbinding the texture unit but this seems like something that ought to be supported by twgl.

I believe the fix is as easy as changing the if statement to be `textureOrPair == null || isTexture(...)`.

Thank you for your time.

**Comment by zackgomez** [comment]
Further note that the webgl1 path would support binding a null texture

![image](https://user-images.githubusercontent.com/354226/204185376-cb939c70-05d2-4c5d-ab5f-e243fa106de4.png)

**Comment by greggman** [comment]
good point!

https://github.com/greggman/twgl.js/commit/f113b4dcca398c1f0b1f69eab475493c122fcadc
