### ISSUE TITLE
m4.scale wrong result 

### ISSUE THREAD

**Issue by fitcool** [greggman/twgl.js#22]
![image](https://cloud.githubusercontent.com/assets/11950654/12488988/38a500be-c07f-11e5-9f47-baae954f1aee.png)

**Comment by gmaker** [comment]
yeap...

**Comment by greggman** [comment]
sadness.

**Comment by gmaker** [comment]
you do the best

**Comment by gmaker** [comment]
you are doing the best

**Comment by greggman** [comment]
Looks good?  This is why I should follow TDD 😱

**Comment by gmaker** [comment]
yeap, thank you. TDD is right way I think

**Comment by greggman** [comment]
pushed 0.0.42
