### ISSUE TITLE
Get the jsdoc into the tsd

### ISSUE THREAD

**Issue by ClementCariou** [greggman/twgl.js#223]
Hello @greggman,

I notice the jsdoc isn't available when hovering functions using browserify / VSCode.
![image](https://github.com/greggman/twgl.js/assets/37800288/f6746131-c698-4fe4-9e8f-4026e045234f)
This is because the generated type definition doesn't contain jsdoc.
![image](https://github.com/greggman/twgl.js/assets/37800288/39dfa358-5a63-4b25-b62b-545817aeea2d)
After adding manually jsdoc to the type definition, the doc become available when hovering the function.
![image](https://github.com/greggman/twgl.js/assets/37800288/ab62d457-3413-4b50-9353-aebf574d4f6f)
I suggest to keep the jsdoc during the type definition generation (even though some might prefer to get a smaller tsd to navigate quickly).

What do you think ?

**Comment by greggman** [comment]
try it now (v5.4.0)

**Comment by ClementCariou** [comment]
Now it works, thank you ! :smiley:
