### ISSUE TITLE
twgl-base package.json refers to non-existent `module` file

### ISSUE THREAD

**Issue by lionello** [greggman/twgl.js#227]
https://github.com/greggman/twgl.js/blob/4cf3d973b79807d09f52115ec5c4930c3c10dc04/npm/base/package.json#L7

This causes errors when running with `vite`:
```
$ npm run build

> c64ify@0.1.0 build
> vite build

vite v4.4.9 building for production...
✓ 22 modules transformed.
✓ built in 271ms
[commonjs--resolver] Failed to resolve entry for package "twgl-base.js". The package may have incorrect main/module/exports specified in its package.json.
error during build:
Error: Failed to resolve entry for package "twgl-base.js". The package may have incorrect main/module/exports specified in its package.json.
```

Remove the line with `module` from `package.json` fixed the build. By the way, `types` also refers to a non-existent file, but this doesn't seem to affect the build.

**Comment by greggman** [comment]
I'll look into fixing it but as quick fix, if you're using any builder that does tree shaking then there isn't much point to using to use base right. It should throw away anything you aren't using.

**Comment by greggman** [comment]
updated v5.5.3
