### ISSUE TITLE
Support Uniform Buffer Objects

### ISSUE THREAD

**Issue by greggman** [greggman/twgl.js#24]
What's the best way for TWGL to support uniform buffer objects?

**Comment by greggman** [comment]
I suppose one issue is testing but I'm assuming calling one function `uniformBlockBinding` and having `twgl.setUniforms` set values in the uniform block would be much faster than it's current. 

Maybe `twgl.createUniformBlock` and `twgl.setUniformBlock(gl, block, uniforms)`.

On the one hand I don't want to impose uniformblocks, on the other hand I want twgl to be terse so as it is now you call twgl.createProgram and it creates the setters etc. I guess again you could call something like `twgl.setDefaults({useUniformBlocks: true})` and it would create uniform block setters instead of uniform setters. An issue though is that you can have multiple uniform blocks so it does get less terse with uniform blocks because twgl can't hide them.

**Comment by greggman** [comment]
Not sure anyone is watching this but ... I tried implementing support for uniform buffer objects. 

It's checked in [here](https://github.com/greggman/twgl.js/tree/webgl2)

Converting twgl-cube to use ubos looks something like this: 

Assuming ubos defined as this

```

uniform View {
  mat4 u_viewInverse;
};

uniform Lights {
  vec3 u_lightWorldPos;
  vec4 u_lightColor;
} lights[2];

uniform Model {
  mat4 u_worldViewProjection;
  mat4 u_world;
  mat4 u_worldInverseTranspose;
} foo;

uniform Material {
  vec4 u_ambient;
  vec4 u_specular;
  float u_shininess;
  float u_specularFactor;
};
```

Then at init time

```
  var programInfo = twgl.createProgramInfo(gl, ["vs", "fs"]);

  var lightUboInfo = twgl.createUniformBlockInfo(gl, programInfo, "Lights[0]");
  var viewUboInfo = twgl.createUniformBlockInfo(gl, programInfo, "View");
  var materialUboInfo = twgl.createUniformBlockInfo(gl, programInfo, "Material");
  var modelUboInfo = twgl.createUniformBlockInfo(gl, programInfo, "Model");
```

To set them you can do this

```
  twgl.setBlockUniforms(lightUboInfo, {
    u_lightWorldPos: [1, 8, -10],
    u_lightColor: [1, 0.8, 0.8, 1],
  };

  twgl.setBlockUniforms(lightUboInfo, {
    u_ambient: [0, 0, 0, 1],
    u_specular: [1, 1, 1, 1],
    u_shininess: 50,
    u_specularFactor: 1,
    u_diffuse: tex,
  });
```

All that does is copy the value into the typedarray that represents the block.  To actually upload the changes and bind the block you need to call

```
    twgl.setUniformBlock(gl, lightUboInfo);
    twgl.setUniformBlock(gl, materialUboInfo);
```

If your block hasn't changed values you can instead just bind

```
    twgl.bindUniformBlock(gl, viewUboInfo);
```

I'm new to UBOs so I don't know best practices but just in case you're new too you need to be aware, they not the same as uniforms in the sense that uniforms are per program. UBOs are *PER MODEL* or whatever other thing you want. 

So in the example above I assumed the `View` UBO you might want to use across programs since view data often does not change (projectMatrix, viewMatrix, ...). `Model` UBO represents the world matrix and anything else that is *per model*. `Material` UBO represents a material so for example in Three.js land you might have one material UBO per material so when you switch materials you just need to bind that material's UBO.  Finally I had a `Light` UBO thinking maybe lights would also work similar to materials, 1 UBO per light set.

The point of all that is, unlike uniforms there are multiple UBOs. They are not just a faster way of setting uniforms. They are a completely different organization scheme. In the example above there would be, 1 ubo for the view, 1 per model, 1 per material, 1 per light set.

There's also another issue which isn't that different from normal uniforms and that is they can disappear if optimized out. I haven't looked up the rules. Checking empirically if a field of a UBO is not used it wasn't removed on Chrome/OSX but if no fields of the UBO were accessed then the whole UBO was optimized out.

I bring that up because twgl is making `ArrayBufferView`s for each uniform. So you can do this

    lightUboInfo.uniforms.u_shininess[0] = someValue;
    lightUboInfo.uniforms.u_specular.set([1, 0, 0, 1]);

But, something gets optimized out (like while you're debugging and you change your shader to output `vec4(1,0,0,1);`  then if you directly access the values the code will break since they won't exist. So it seems better to set the uniforms with

    twgl.setBlockUniforms(lightUboInfo, {
       u_shininess: someValue,
       u_specular: [1, 0, 0, 1],
    });

Since it can ignore non-existent uniforms. On the other hand direct access would be slightly faster.

**Comment by greggman** [comment]
Checked in

http://twgljs.org/examples/uniform-buffer-objects.html

**Comment by munrocket** [comment]
@greggman this is really cool!
