### ISSUE TITLE
Support Uint8ClampedArray

### ISSUE THREAD

**Issue by Thecontrarian** [greggman/twgl.js#25]
when i try to use Uint8ClampedArray, twgl throws an "unsupported typed array type" error.

**Comment by greggman** [comment]
I put up a patch. Here's one to try

https://github.com/greggman/twgl.js/tree/uint8clampedarray/dist

**Comment by greggman** [comment]
So I actually made a sample and saw that WebGL itself doesn't currently allow `Uint8ClampedArray` for textures. I made twgl workaround that. The current patch should work.

**Comment by greggman** [comment]
I published a new version that seems to support Uint8ClampedArrays

Here's a test

http://twgljs.org/examples/clamped-array.html

**Comment by Thecontrarian** [comment]
great, thanks!
