### ISSUE TITLE
Support draw states

### ISSUE THREAD

**Issue by andrewhills** [greggman/twgl.js#26]
So I've got two ideas for managing draw states.
[implementation](http://pastebin.com/T1sBASuA)

***The first is similar to how you are managing uniforms:***
Basically it will set the states specified in the first param. 

Also if the second optional parameter is true, any unspecified state will be set to their initial states. 

```
mygl.states({
  "blend" : true,
  "blend_src" : gl.SRC_ALPHA,
  "blend_dst" : gl.ONE_MINUS_SRC_ALPHA,
},true);
```
 
***The second more similar to gl***

```
mygl.clearStates(); //set states to be set to initial values
mygl.enable(gl.BLEND);
mygl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);
mygl.applyStates(); //actually call state functions
```

***There is also a sync states method so it can be used with other libraries/code that might also be setting states:***
```
mygl.syncStates();
```

***edit:***
Just modified how the first example worked.

**Comment by greggman** [comment]
Sorry if I didn't get back to you before. I didn't want to be discouraging but I'm not sure this is much of a plus/fit for twgl. It doesn't seem all that much less verbose. It's basically one or more lines per line of webgl. 

Take your example

```
mygl.states({
  "blend" : true,
  "blend_src" : gl.SRC_ALPHA,
  "blend_dst" : gl.ONE_MINUS_SRC_ALPHA,
},true);
```

vs

```
gl.enable(gl.BLEND);
gl.blendFunc(gl.SRC_ALPHA, gl.ONE_MINUS_SRC_ALPHA);
```

5 lines vs 2.  

I get that you can do this

```
var someStates = {
  "blend" : true,
  "blend_src" : gl.SRC_ALPHA,
  "blend_dst" : gl.ONE_MINUS_SRC_ALPHA,
};
```

and then later

```
mygl.states(someStates);
```

But you should just as easily do

```
function setSomeStates() {
  gl.enable(gl.BLEND);
  gl.blendFunc(gl.SRC_ALPHA, gl.ONE_MINUS_SRC_ALPHA);
}
```

and later

```
setSomeStates();
```

it seems like the only thing that's gained is tracking the GL states (reset, sync, etc) which is cool but not common (at least in my experience)

In any case is there any reason to add it to twgl? So far twgl tracks no state. You can mix in standard webgl anywhere. Example:

     var tex1 = twgl.createTexture(gl, { src: "foo.jpg" });
     var tex2 = gl.createTexture();

They're the same, both just return a `WebGLTexture` object. Similarly for other stuff

     var programInfo = twgl.createProgramInfo(gl, ["vs", "fs"]);
     var colorLocation = gl.getUniformLocation(programInfo.program, "u_color");
     gl.useProgram(programInfo.program);
     twgl.setUniforms(programInfo, { u_matrix: someMatrix });
     gl.uniform4f(colorLocation, 1, 0, 0, 1);

twgl isn't tracking any state. With your library though suddenly you're required to go through it for it ti work.

    mygl.states(someStates);
    gl.disable(gl.BLEND);

The state inside mygl no longer matches the actual state.

Why not just have a separate `webglstatelib.js` for those people that need state tracking?

**Comment by andrewhills** [comment]
Ah right, yeah I thought it would be nice to have an all in one library, but I understand you not wanting to incorporate it if you're going for no state tracking / working with standard GL.

I've always had trouble managing my draw states in GL, even when writing code like your setSomeStates(), but it doesn't sound like you have those problems. Maybe I'll just make it into a stand alone library like you said.

I was actually trying to delete the issue when I closed/opened it (hope you didn't think I was getting angry), turns out you can't delete these things.

So I'll just close it here then.
