### ISSUE TITLE
twgl.min.js minified npm package

### ISSUE THREAD

**Issue by richtr** [greggman/twgl.js#27]
The npm twgl.js package that is available at https://www.npmjs.com/package/twgl.js seems to allow only import of the full version of the library (with 3d math and primitives included).

Is it possible to `npm install` the minimum version from somewhere?

**Comment by greggman** [comment]
does this work?

https://www.npmjs.com/package/twgl-base.js

**Comment by richtr** [comment]
Yes, it does!

Thank you for the quick turnaround 👍
