### ISSUE TITLE
Exception when compiling program w/o opt_attribs

### ISSUE THREAD

**Issue by Olliebrown** [greggman/twgl.js#31]
The version on the main web page and downloaded as the latest release has a bug where it raises an exception when you try to compile a program without providing the 'opt_attribs'

To reproduce: open the tiny.js example and notice it does not work.

Problem seems to be around twgl.js:1823:

>} else if (!Array.isArray(opt_attribs)) { var options = opt_attribs;
>      opt_errorCallback = options.errorCallback;
>      opt_attrib = options.attribLocations;
>    }

Quick fix is to check that opt_attribs is defined before checking if it is an array:

>    } else if (opt_attribs && !Array.isArray(opt_attribs)) {
>      var options = opt_attribs;
>      opt_errorCallback = options.errorCallback;
>      opt_attribs = options.attribLocations;
>    }

Also, notice that the last line of the conditional block referenced 'opt_attrib' w/o an 's' which I think is a type-o.  I assume it should be 'opt_attribs'

**Comment by Olliebrown** [comment]
Note, the relevant line in the src is in programs.js:435:

>    } else if (!Array.isArray(opt_attribs)) {
>      var options = opt_attribs;
>      opt_errorCallback = options.errorCallback;
>      opt_attrib = options.attribLocations;
>    }

**Comment by greggman** [comment]
Sorry about that. I think it's fixed now.
