### ISSUE TITLE
WebGL 2

### ISSUE THREAD

**Issue by backspaces** [greggman/twgl.js#36]
It looks like webgl2 is spreading fast, http://webglreport.com/?v=2

Maybe use this as a chance to upgrade to webgl2 *and* es6 modules *and* modular shaders (template strings)? I guess that'd bump us to twglThree!

Man what I'd give for a ThreeCore.js. Yes, Three is great in many ways but is pretty hard to adapt to one's own needs. I have zero idea of their architecture such as "Do they to their transforms in the GPU?" or "Can I use ColorMaps so that color is just a small int into a color array uniform?".

**Comment by greggman** [comment]
switching to es6 might happen. 

modular shaders seems like something another library would do, for example https://mattdesl.svbtle.com/glslify

**Comment by greggman** [comment]
BTW webgl2 has already been added and there's a few examples posted. Not sure what else to add.

**Comment by backspaces** [comment]
Ah..I didn't dig deeply enough .. didn't see the webgl2 use. And modular shaders are pretty easy via template strings.

**Comment by greggman** [comment]
I should warn you Chrome 55 had a spec noncompliant version of `texSubImage3D` which twgl was using. It's removed in future versions of Chrome. I've fixed the code to be spec compliant but it means that code doesn't run in Chrome 55. It does run in Chrome 57 (haven't tried 56)
