### ISSUE TITLE
twgl.js on npm is version 1.9.0

### ISSUE THREAD

**Issue by Stuk** [greggman/twgl.js#39]
Despite [twgl](https://www.npmjs.com/package/twgl.js) being updated on npm and saying it's 2.8.2, the version in `dist/twgl.js` is actually 1.9.0!

**Comment by Stuk** [comment]
The version in [twgl-base.js](https://www.npmjs.com/package/twgl-base.js) is correct

**Comment by greggman** [comment]
fixed I think

**Comment by Stuk** [comment]
Just checked and it looks good now, thanks!
