### ISSUE TITLE
WebGLSampler is undefined in WebGL1

### ISSUE THREAD

**Issue by edankwan** [greggman/twgl.js#41]
At the moment if I am using non-WebGL2 supported browsers, it dies at
https://github.com/greggman/twgl.js/blob/d848b7555d950b9ce943dfd1007dacba4f9b9516/src/textures.js#L622

It is a pretty minor issue and I can do `wrapS` and `wrapT` separately for temporary fix but I just want to flag it in case you want to fix it.

**Comment by greggman** [comment]
Doh! Does this fix it?
https://github.com/greggman/twgl.js/commit/fa00ea2633fdfe2cb7f4fbd512bfbbdad1bcc7a4

**Comment by edankwan** [comment]
I haven't tried it yet but it looks like there is a typo: `window.WebGLSampeler`

**Comment by edankwan** [comment]
No worry. I believe the best way to test is to drive more people to use the library.
