### ISSUE TITLE
3x3 Matrices?

### ISSUE THREAD

**Issue by fuzzyTew** [greggman/twgl.js#48]
It's unobvious from the twgl docs how to pass in a mat3 uniform.  I need to construct it by hand as a Float32Array of length 9, correct?  What would be the "ideal" solution?

**Comment by greggman** [comment]
Unless there's a bug it should just be either a `Float32Array` or a standard JavaScript array
 
      var some9ElementJSArray = [1, 2, 3, 4, 5, 6, 7, 8, 9];
      var some9ElementFloat32Array = new Float32Array([11, 12, 13, 14, 15, 16, 17, 18, 19]);

      twgl.setUniforms(someProgramInfo, {
         someMat3Uniform: some9ElementJSArray,
         someOtherMat3Uniform: some9ElementFloat32Array,
      });

**Comment by fuzzyTew** [comment]
Thanks.  I was thinking of starting to write up an m3.js, but that's probably overkill.  I'm using a normal matrix as in http://graphics.cs.wisc.edu/WP/cs559-fall2016/2016/11/02/how-to-compute-a-normalmatrix-in-twgl/ ... it's too bad about the extra calculations inverting a 4x4 matrix when only a 3x3 matrix is needed.
