### ISSUE TITLE
TextureOptions : level

### ISSUE THREAD

**Issue by mserege** [greggman/twgl.js#52]
Hi, I'm really enjoying using Twgl. I'm just missing one thing for now. I'm providing texture mipmaps myself and I would like to call setTextureFromArray with a specified level. Would it be possible to:
- add a "level" property to TextureOptions type
- use this property if provided when calling gl.texImage2D and gl.texImage3D

I tried it successfully but I'm unsure about any consequences in other use cases.

Thanks in advance!

**Comment by greggman** [comment]
Sounds good to me!

You want to add it or you want me to add it? I'll add it everywhere

**Comment by mserege** [comment]
Cool! I let you add it everywhere. Thanks

**Comment by mserege** [comment]
Amazing! Just tried and it's just perfect. Could you push this new version to npm?

**Comment by greggman** [comment]
pushed it
