### ISSUE TITLE
use instancing with draw object list

### ISSUE THREAD

**Issue by MHA15** [greggman/twgl.js#55]
hi
thanks for adding addExtensionsToContext now we can use instancing but there is a problem 
drawObjectList can not draw instance objects I will be happy if you add it as soon as possible and when I want to draw it manually as like [the example](twgljs.org/examples/instancing.html) before or after the drawObjectList called, it make bad thing and it would not draw other objects correctly. please help me fix it
Thanks you

**Comment by MHA15** [comment]
anybody there?

What is the bug?

why it would not working?
`gl.useProgram(obj1.programInfo.program);
twgl.setBuffersAndAttributes(gl, obj1.programInfo , obj1.bufferInfo);
twgl.setUniforms(obj1.programInfo, uniforms);
gl.drawArraysInstanced(obj1.type, 0, 4, obj1Count);

gl.useProgram(obj2.programInfo.program);
twgl.setBuffersAndAttributes(gl, obj2.programInfo , obj2.bufferInfo);
twgl.setUniforms(obj2.programInfo, uniforms);
gl.drawArrays(obj2.type, 0, obj2Count);`

**Comment by greggman** [comment]
You need to use vertex array objects OR you need to manually set the divisors back to zero some other way.

You can make `VertexArrayInfo` from [the example](https://github.com/greggman/twgl.js/blob/feb2aa98ee112afcb77350521880009a7d24f55e/examples/instancing.html#L184) like this

      const bufferInfo = twgl.createBufferInfoFromArrays(gl, arrays);
      const vertexArrayInfo = twgl.createVertexArrayInfo(gl, programInfo, bufferInfo);

And use them like this

```
gl.useProgram(obj1.programInfo.program);
twgl.setBuffersAndAttributes(gl, obj1.programInfo , obj1.vertexArrayinfo);
twgl.setUniforms(obj1.programInfo, uniforms);
gl.drawArraysInstanced(obj1.type, 0, 4, obj1Count);

gl.useProgram(obj2.programInfo.program);
twgl.setBuffersAndAttributes(gl, obj2.programInfo , obj2.vertexArrayInfo);
twgl.setUniforms(obj2.programInfo, uniforms);
gl.drawArrays(obj2.type, 0, obj2Count);`
```

**Comment by greggman** [comment]
v3.7.0 supports using `drawBufferInfo` or `drawObjectList`. Updated [example](https://github.com/greggman/twgl.js/blob/835cdd52bf3927c4df1b1928374a51975b48e944/examples/instancing.html#L200)

**Comment by MHA15** [comment]
thank you so much

**Comment by MHA15** [comment]
I have tried new version with this code but it make a error
Code:
`
twgl.drawObjectList(gl,obj);
`
Error:
`
glDrawArrays: attempt to access out of range vertices in attribute 0
`

but it works simply by this code
`
gl.useProgram(obj[0].programInfo.program);
    twgl.setBuffersAndAttributes(gl, obj[0].programInfo , obj[0].vertexArrayInfo);
    twgl.setUniforms(obj[0].programInfo, uniforms);
    gl.drawArraysInstanced(obj[0].type, 0, 160, EdgeCount);
`

I had read the source and I think you give `gl.drawArraysInstanced` 5 of parameters but I give it 4 and it works?
