### ISSUE TITLE
support arrayBuffer and sharedArryaBuffer

### ISSUE THREAD

**Issue by MHA15** [greggman/twgl.js#61]
hi

I had saw [mdn page of sharedArryaBuffer](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjKjsLSntnWAhVkApoKHe3VDWsQFggkMAA&url=https%3A%2F%2Fdeveloper.mozilla.org%2Ffa%2Fdocs%2FWeb%2FJavaScript%2FReference%2FGlobal_Objects%2FSharedArrayBuffer&usg=AOvVaw2Fu5DyH5_t9fXYDbX7lQQE) and it's says it can be use with webgl2 and for reasons I'm using buffers directly with typedArray views. so it's a good feature to support buffers instead of typed arrays .

thank you so much

**Comment by MHA15** [comment]
is this going to be add on next versions?

**Comment by greggman** [comment]
added

**Comment by MHA15** [comment]
it is look like that typedArrays.isArrayBuffer(new ArrayBuffer(24)) will return undefined which is not good!!?? :(

**Comment by greggman** [comment]
isArrayBuffer has never allowed ArrayBuffer, it only allows ArrayBufferViews

**Comment by MHA15** [comment]
and why? There is no limit in webgl for this?

**Comment by MHA15** [comment]
@greggman 
can you here me?
we can have a buffer with more than one view on it (for c type structs) and it can directly use in webgl why should twgl Take it away?
