### ISSUE TITLE
Uniform blocks are buggy in current Chrome for Windows

### ISSUE THREAD

**Issue by karelp** [greggman/twgl.js#69]
The demo for uniform blocks exhibits the issue: http://twgljs.org/examples/uniform-buffer-objects.html

Not sure if this is a bug in Chrome 64 on Windows or in TWGL. The demo seems to work properly in other browsers, even Blink based ones such as Opera.

**Comment by greggman** [comment]
I'm guessing it's a bug in Chrome. Chrome 64 as of today doesn't run for me at all. I just get a black window when it starts. Not this page in particular, it just opens a black window, no UI, no URL bar, nothing.

**Comment by karelp** [comment]
I just tried Chrome 63 (latest stable) and it also has this problem. I reported it, hopefully it will get fixed soon.

**Comment by greggman** [comment]
what:s the bug #?

**Comment by greggman** [comment]
oh btw I checked today and it's working for me in 65.0.3293.1 (Official Build)

my about:gpu

```

Data exported | 12/13/2017, 9:03:45 AM
-- | --
Chrome version | Chrome/65.0.3293.1
Operating system | Windows NT 10.0.16299
Software rendering list URL | https://chromium.googlesource.com/chromium/src/+/ac08ea56171f2ac1359e002fe7e5a19a32411636/gpu/config/software_rendering_list.json
Driver bug list URL | https://chromium.googlesource.com/chromium/src/+/ac08ea56171f2ac1359e002fe7e5a19a32411636/gpu/config/gpu_driver_bug_list.json
ANGLE commit id | a98a28112b0e
2D graphics backend | Skia/65 106e17aa38c9cf90c864232ae8dc7667f37bb787-
Command Line | "C:\Users\gregg\AppData\Local\Google\Chrome SxS\Application\chrome.exe" --flag-switches-begin --flag-switches-end


```

**Comment by karelp** [comment]
The fix apparently got to Chrome stable as well, everything is working fine now. Thanks for investigating!
