### ISSUE TITLE
Create cube map texture from array of elements

### ISSUE THREAD

**Issue by mserege** [greggman/twgl.js#73]
We already can create a cube map texture from an array of strings or an array of buffers but I would like to create it from an array of html elements. Would it be possible to add this feature?

Thanks in advance!

**Comment by greggman** [comment]
You can't create textures from generic html elements. Only Image, Video, Canvas, and ImageBitmap. That's just a limit of the browser period. If you want to create textures from HTML about the best you can do is use something like HTM2Canvas

https://html2canvas.hertzen.com/

Or did you mean an array of compatible elements like image, video, canvas etc??

**Comment by mserege** [comment]
I meant an array of compatible elements like setTextureFromElement but with an array of HTMLElement representing faces of cube map.

**Comment by greggman** [comment]
4.4.0 should do this? Example in https://twgljs.org/examples/textures.html

**Comment by mserege** [comment]
Perfect! Would you mind pushing 4.4.0 to npm?
