### ISSUE TITLE
CubemapReadyCallback called with wrong parameters order

### ISSUE THREAD

**Issue by mserege** [greggman/twgl.js#74]
Hi,

FYI, loadCubemapFromUrls method calls a its callback with wrong parameters order.

`callback(errors.length ? errors : undefined, imgs, tex);` should be
`callback(errors.length ? errors : undefined, tex, imgs);` as defined in CubemapReadyCallback definition.

Same thing with loadSlicesFromUrls method and ThreeDReadyCallback definition.

**Comment by greggman** [comment]
thanks. Fixed in 4.4.0?

**Comment by mserege** [comment]
Yes. Perfect!
