### ISSUE TITLE
The buffer can't handle obj with elements more than 16K values

### ISSUE THREAD

**Issue by Jonathan-D-Ip** [greggman/twgl.js#77]
https://github.com/greggman/twgl.js/blob/761ec5fa99aef5a40f8010059f8ca0e0cd40a7e9/src/attributes.js#L179

Inside the "createBufferInfoFromArrays", you may get the number of vertex. If the vertex count is greater than 16384. Then, the type of the element index would be 0x1405. So, at this line we can check the type of element before setting the type value, rather than hard coding it to Uint16Array

**Comment by greggman** [comment]
I'm not sure what you mean. By default WebGL can only handle indices of gl.UNSIGNED_SHORT (max index 65535 not 16384). If you want to use gl.UNSIGNED_INT then you need to enable that extension and then either pass a Uint32Array as your indices
  
    indices: new Uint32Array(indices),

 to twgl or else set the type

     indices: { type: Uint32Array, javaScriptArrayOfIndices }
