### ISSUE TITLE
is there a plan to support using interleaved array to create buffer?

### ISSUE THREAD

**Issue by steve3d** [greggman/twgl.js#83]
three.js has this feature to create a InterleavedBuffer from array, [here](https://threejs.org/docs/index.html#api/core/InterleavedBuffer),  this type of buffer is much more common, so I'm wondering if the twgl will support this type of buffer creating?

**Comment by greggman** [comment]
Much more common? I know of almost zero webgl demos that interleave data and if you use VAOs which is supported on 99% of WebGL machines and the 1% that can't is probably too slow to run your content anyway well then what's the point?

But in any case what do you want to happen? twgl can't pack the data for you. It takes more work to specify how you want it packed than it does to pack it yourself so there would be no point. See

https://github.com/greggman/twgl.js/blob/master/examples/packed-arrays.html

You can pass offsets and strides to twgl. 

http://jsfiddle.net/greggman/03k5ztsu/

See the [array spec](http://twgljs.org/docs/module-twgl.html#.FullArraySpec) and/or [bufferinfo attributes](http://twgljs.org/docs/module-twgl.html#.AttribInfo)

**Comment by steve3d** [comment]
sorry, I mean common on desktop graphics,

and I'm new to webgl programming, so I have not deeply read the docs.

anyway, thank you for the info.
