### ISSUE TITLE
Allow accepting `internalFormat` option in `createFramebufferInfo`

### ISSUE THREAD

**Issue by wdanilo** [greggman/twgl.js#93]
Currently, when using `createFramebufferInfo` we need to provide `format` option, which is inconsistent with other functions in TWGL. When using `createTextures` we can skip the `format` param and use `internalFormat` instead, so `format` would be inferred automatically. This is often desirable as both `format` as well as `type` can be inferred from `internalFormat` (but not the other way around), so it's simple to just keep `internalFormat` as a config in a library. Would it be possible to also infer `format` when `internalFormat` is provided in `createFramebufferInfo`?

**Comment by greggman** [comment]
I'm pretty sure you can supply an internalFormat. A quick test

http://jsfiddle.net/greggman/5xrgof1v/

**Comment by wdanilo** [comment]
Oh damn, you're right. I'm sorry for creating an invalid issue. I was reading the sources and somehow I was sure that without passing the format explicitly it would not work correctly. Thank you for proving me wrong!

**Comment by baturinsky** [comment]
It's not accepted in Typescript, though, because d.ts definition of AttachmentOptions misses this parameter.
